
from __future__ import annotations
from typing import Protocol, Mapping, Any
import numpy as np

class SimulationAdapter(Protocol):
    def n_variables(self) -> int: ...
    def n_objectives(self) -> int: ...
    def bounds(self) -> list[tuple[float, float]]: ...
    def run(self, x: np.ndarray, context: Mapping[str, Any] | None = None) -> np.ndarray: ...
